# Generated by Django 5.2 on 2025-05-22 14:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0002_alter_blog_tags"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                related_name="liked_comments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuarios que dieron me gusta",
            ),
        ),
    ]
