# Generated by Django 4.1 on 2025-04-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0002_alter_review_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="tag",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
