# Generated by Django 3.2 on 2025-05-19 05:36

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_alter_blog_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(default='Escribe aquí tu contenido...', help_text='Editor completo con soporte para imágenes', verbose_name='Contenido'),
        ),
    ]
