# Generated by Django 3.2 on 2025-05-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_alter_blog_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#3B82F6', help_text='Color en formato HEX (ej: #3B82F6)', max_length=7, verbose_name='Color del Tag'),
        ),
    ]
