# Generated by Django 4.1 on 2025-04-21 01:31

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0003_blog_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="contenido",
            field=ckeditor.fields.RichTextField(default="Default content goes here..."),
        ),
        migrations.AddField(
            model_name="blog",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="blog_images/"),
        ),
    ]
