# Generated by Django 4.1 on 2025-05-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0004_blog_contenido_blog_imagen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
