# Generated by Django 4.1 on 2025-05-11 18:10

import blogapp.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blogapp", "0005_alter_blog_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="blog",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Entrada de Blog",
                "verbose_name_plural": "Entradas de Blog",
            },
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={
                "verbose_name": "Comentario",
                "verbose_name_plural": "Comentarios",
            },
        ),
        migrations.AlterModelOptions(
            name="review",
            options={"verbose_name": "Reseña", "verbose_name_plural": "Reseñas"},
        ),
        migrations.RemoveField(
            model_name="blog",
            name="contenido",
        ),
        migrations.AlterField(
            model_name="blog",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Autor",
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(
                default="Escribe aquí tu contenido...", verbose_name="Contenido"
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Fecha de creación"
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="imagen",
            field=models.ImageField(
                blank=True,
                help_text="Formatos soportados: JPG, PNG (máx. 2MB)",
                null=True,
                upload_to="blog_images/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp"]
                    ),
                    blogapp.models.validate_image_size,
                ],
                verbose_name="Imagen destacada",
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="tag",
            field=models.CharField(
                blank=True,
                help_text="Etiqueta para categorización (opcional)",
                max_length=50,
                null=True,
                verbose_name="Etiqueta",
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="title",
            field=models.CharField(
                help_text="Ingrese un título descriptivo (máx. 255 caracteres)",
                max_length=255,
                verbose_name="Título del Blog",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="commenter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Comentarista",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.TextField(
                help_text="Escribe tu comentario", verbose_name="Contenido"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Fecha de creación"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="review",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="blogapp.review",
                verbose_name="Reseña asociada",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="blog",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="blogapp.blog",
                verbose_name="Blog asociado",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="comment",
            field=models.TextField(
                help_text="Escribe tu opinión detallada", verbose_name="Comentario"
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Fecha de creación"
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.IntegerField(
                default=3,
                help_text="Valor entre 1 (peor) y 5 (mejor)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Calificación",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="reviewer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Revisor",
            ),
        ),
        migrations.AddIndex(
            model_name="blog",
            index=models.Index(fields=["title"], name="blogapp_blo_title_724185_idx"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
