# Generated by Django 4.2.21 on 2025-05-11 22:34

import blogapp.models
import ckeditor_uploader.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blogapp", "0006_alter_blog_options_alter_comment_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre único para la categorización",
                        max_length=50,
                        unique=True,
                        verbose_name="Nombre del Tag",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#3B82F6",
                        help_text="Color en formato HEX (ej: #3B82F6)",
                        max_length=7,
                        verbose_name="Color del Tag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Etiqueta",
                "verbose_name_plural": "Etiquetas",
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Comentario",
                "verbose_name_plural": "Comentarios",
            },
        ),
        migrations.AlterModelOptions(
            name="review",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Reseña",
                "verbose_name_plural": "Reseñas",
            },
        ),
        migrations.RemoveField(
            model_name="blog",
            name="imagen",
        ),
        migrations.RemoveField(
            model_name="blog",
            name="tag",
        ),
        migrations.AddField(
            model_name="blog",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Formatos soportados: JPG, PNG, WEBP (máx. 2MB)",
                null=True,
                upload_to="blog_images/%Y/%m/%d/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp"]
                    ),
                    blogapp.models.validate_image_size,
                ],
                verbose_name="Imagen destacada",
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blogs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Autor",
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="content",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                default="Escribe aquí tu contenido...",
                help_text="Editor completo con soporte para imágenes",
                verbose_name="Contenido",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="commenter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Comentarista",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.IntegerField(
                choices=[
                    (1, "★☆☆☆☆"),
                    (2, "★★☆☆☆"),
                    (3, "★★★☆☆"),
                    (4, "★★★★☆"),
                    (5, "★★★★★"),
                ],
                default=3,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Calificación",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="reviewer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Revisor",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("blog", "reviewer")},
        ),
        migrations.AddIndex(
            model_name="blog",
            index=models.Index(
                fields=["created_at"], name="blogapp_blo_created_d6b789_idx"
            ),
        ),
        migrations.AddField(
            model_name="blog",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Seleccione las etiquetas correspondientes",
                to="blogapp.tag",
                verbose_name="Etiquetas",
            ),
        ),
    ]
